development:
  adapter: postgresql
  encoding: unicode
  database: smalltalk
  pool: 5
  username: alok
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: smalltalk
  pool: 5
  username: alok
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: smalltalk
  pool: 5
  username: alok
  password:
